### ndarray Task

In [23]:
import numpy as np

#1 1~10까지의 요소를 ndarray에 담는다.
# ndarray1 = np.array([i for i in range(1, 11)])
ndarray1 = np.array(list(range(1, 11)))
print(type(ndarray1), ndarray1.shape, ndarray1.ndim, ndarray1.dtype, sep="\n")

print("=" * 50)

#2 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1을 담는다.
python_list = []
python_list.append([6 - i for i in range(2)])
python_list.append([4 - i for i in range(2)])
python_list.append([2 - i for i in range(2)])

ndarray2 = np.array(python_list)
print(type(ndarray2), ndarray2.shape, ndarray2.ndim, ndarray2.dtype, sep="\n")

print("=" * 50)

#3 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다(transpose, 전치).
ndarray3 = np.array([[(5 - i) * 2 for i in range(4)]]).T
print(type(ndarray3), ndarray3.shape, ndarray3.ndim, ndarray3.dtype, sep="\n")

print("=" * 50)

# #1에서 제작된 ndarray의 요소 타입 출력
print(ndarray1.dtype)

print("=" * 50)

# #1에서 제작된 ndarray의 차원 출력
print(ndarray1.shape)

print("=" * 50)

# #2에서 제작된 ndarray의 요소 타입을 float으로 변환
ndarray2_float32 = ndarray2.astype(np.float32)
print(ndarray2_float32)

print("=" * 50)

# #2에서 제작된 ndarray의 차원 출력
print(ndarray2.shape)

print("=" * 50)

# #3에서 제작된 ndarray의 요소 타입을 int8로 변환
ndarray2_int8 = ndarray2.astype(np.int8)
print(ndarray2_int8.dtype, ndarray2_int8, sep="\n")

print("=" * 50)

# #3에서 제작된 ndarray의 요소에 5씩 더하기
ndarray3_result = ndarray3 + 5
print(ndarray3_result)

print("=" * 50)

# #3에서 제작된 ndarray의 차원 출력
print(ndarray3.shape)

<class 'numpy.ndarray'>
(10,)
1
int32
<class 'numpy.ndarray'>
(3, 2)
2
int32
<class 'numpy.ndarray'>
(4, 1)
2
int32
int32
(10,)
[[6. 5.]
 [4. 3.]
 [2. 1.]]
(3, 2)
int8
[[6 5]
 [4 3]
 [2 1]]
[[15]
 [13]
 [11]
 [ 9]]
(4, 1)


### arange, zeros, ones Task

In [29]:
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32 인 ndarray 만들기
ndarray = np.zeros((10, ), dtype=np.int32)
print(ndarray, ndarray.dtype, ndarray.shape)

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray = np.ones((3, 4), dtype=np.int8)
print(ndarray, ndarray.dtype, ndarray.shape)

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray = np.arange(5)
print(ndarray, ndarray.dtype, ndarray.shape)

[0 0 0 0 0 0 0 0 0 0] int32 (10,)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int8 (3, 4)
[0 1 2 3 4] int32 (5,)


### reshape Task

In [41]:
ndarray1 = np.arange(start=0, stop=16)
ndarray1

print("=" * 50)

# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2.shape, ndarray2, sep="\n")

print("=" * 50)

# 2 Dimension, axis 0은 8로 변경
ndarray3 = ndarray1.reshape((8, -1))
print(ndarray3.shape, ndarray3, sep="\n")

print("=" * 50)

# 3 Dimension으로 변경
ndarray4 = ndarray1.reshape((4, 2, -1))
print(ndarray4.shape, ndarray4, sep="\n")

print("=" * 50)

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray5 = ndarray4.reshape((-1, 1))
print(ndarray5.shape, ndarray5, sep="\n")

print("=" * 50)

# ndarray3을 1 Dimension으로 변환
ndarray6 = ndarray4.reshape((-1,))
print(ndarray6.shape, ndarray6, sep="\n")

(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(4, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
(16, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
(16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Indexing Task

In [2]:
import numpy as np
# 1-2. 3차원 위치 인덱싱(Location indexing)
# 1~9까지 3차원 dimension axis0이 3일때 5의 값 찾기
ndarray1 = np.arange(start=1, stop=10)
ndarray2 = ndarray1.reshape((3, -1,1))
print(ndarray2)
print(ndarray2[1,1,0])

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
5


In [4]:
# 2-2. 3차원 슬라이싱(Slicing)
# 면,행,렬 순으로 생각

ndarray1 = np.arange(start=1, stop=28)
print(ndarray1)

print("=" * 30)

ndarray2 = ndarray1.reshape((3, 3,-1))
print(ndarray2)

# print("=" * 30)

# print(ndarray2[:4, :2,1:])

# print("=" * 30)

# print(ndarray2[0:2])

# print("=" * 30)

# print(ndarray2[2:, :])

# print("=" * 30)

# print(ndarray2[:])

# print("=" * 30)

print(ndarray2[-2:-1, 0:2])

print("=" * 30)

print(ndarray2[::-1])

print("=" * 30)

print(ndarray2[::-1, ::-1,::-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[10 11 12]
  [13 14 15]]]
[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
[[[27 26 25]
  [24 23 22]
  [21 20 19]]

 [[18 17 16]
  [15 14 13]
  [12 11 10]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]


In [121]:
# 3. 3차원 팬시 인덱싱(Fancy indexing)

ndarray1 = np.arange(start=1, stop=21)
print(ndarray1[[4,3]])

ndarray1 = np.arange(start=1, stop=21)
ndarray2 = ndarray1.reshape((2,2,5))
print(ndarray2)

print(ndarray2[[1,0], 0:1])
print(ndarray2[[0,1],[0,1],[0,1]])

# 2차원 ndarray에서 행과 열 모두 팬시 인덱싱을 사용하면, 해당 좌표의 열백터를 가져온다.
# ndarray2[[x1, x2], [y1, y2]] : (x1, y1), (x2, y2) : [x, y]

#[]인덱스 안에 모두 인덱싱을 사용하면 대칭되는 좌표를 가져옴


#[[index,index...]] -> axis0의 index에 해당하는 값으로 만들어진 ndarray 리턴
#[[index,index...],] -> 배열의 인덱스에 해당하는 axis를 기준으로 원본 배열의 대칭 axis에서 index에 해당하는 인덱스의값으로 새로운  ndarray 리턴
print(ndarray2[[1,0]])
print(ndarray2[[1],[1]])

print("===============")
print(ndarray2[[1,1,1,0],[0,1,0,1],[0,1,0,2]]) # 처음 배열안에 하나의 배열만 있으므로 axis0에 대한 기준으로 인덱스 1인 값을 세개 가져와 ndarray로 리턴
print(ndarray2[1,1,1])  #직접적인 인덱스 접근해서 값 가져오기 

[5 4]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[11 12 13 14 15]]

 [[ 1  2  3  4  5]]]
[ 1 17]
[[[11 12 13 14 15]
  [16 17 18 19 20]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
[[16 17 18 19 20]]
[11 17 11  8]
17


In [5]:
# 4. 불린 인덱싱(Boolean indexing)
#-50~49의 연속된 수를 3차원 행렬로 만든 후 음수 값만 추출
ndarray1 = np.arange(start=-50, stop=50, step=1)

ndarray2 = ndarray1.reshape((2,2,-1))
print(ndarray2)

print(ndarray2*(-1)>0)
print(ndarray2[ndarray2*(-1)>0])

ndarray1 = np.arange(3)
print(ndarray1)
print(ndarray1[[False, True,True]])

#인덱싱 자리에 불린 배열로 필터링 가능 위치 갯수 같아야함.


[[[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34
   -33 -32 -31 -30 -29 -28 -27 -26]
  [-25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9
    -8  -7  -6  -5  -4  -3  -2  -1]]

 [[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16
    17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
    42  43  44  45  46  47  48  49]]]
[[[ True  True  True  True  True  True  True  True  True  True  True
    True  True  True  True  True  True  True  True  True  True  True
    True  True  True]
  [ True  True  True  True  True  True  True  True  True  True  True
    True  True  True  True  True  True  True  True  True  True  True
    True  True  True]]

 [[False False False False False False False False False False False
   False False False False False False False False False False False
   False False False]
  [False False False False False False False False False False False
   False False Fa

In [6]:
# np.sort(ndarray) 원본 행렬에서 정렬된 새로운 행렬 리턴

original_ndarray = np.array([i for i in range(20,0,-1)])
print(original_ndarray)
original_ndarray = original_ndarray.reshape(2,2,-1)

#열에 대한 오름차순 정렬 (기본값 axis=0) 같은 행의 값을 비교해 작은 값부터 오름차순 정렬 
sorted_ndarray = np.sort(original_ndarray)
print(f"원본 배열: {original_ndarray}")
print(f"정렬된 배열: {sorted_ndarray}")

#np.sort의 axis는 기본값이 -1 이므로 항상 열에대한 정렬

#면에대한 오름차순 정렬, 면의 입장에서 행과 열이 같은 다른면의 값과 비교해 작은 값부터 오름차순 정렬
sorted_ndarray = np.sort(original_ndarray,axis=0)
print(sorted_ndarray)

#행에 대한 오름차순 정렬 , 같은 열의 값을 비교해 같은 작은 값부터 오름차순 정렬
original_ndarray = np.array([[6,3,8],[2,5,1]])
print(np.sort(original_ndarray,axis=0))


#ndarray.sort() 원본 행렬 정렬, 리턴값 없음
print(original_ndarray.sort(axis=0))
print(original_ndarray)

#np.argsort(ndarray) -> 정렬 후 해당 값의 정렬전 인덱스 배열 리턴
np.argsort(original_ndarray)
print(original_ndarray)



ngarray = np.array([1,0,3,2,4,5,2,1])

#정렬 후 해당 값의 정렬전 인덱스배열을 활용해 정렬전의 배열을 펜시 인덱싱으로 정렬하기
sorted_array = ngarray[np.argsort(ngarray)]
print(sorted_array)


#행은 위에서 아래, 열은 왼쪽에서 오른쪽, 면은 뒤에서 앞으로 방향 생각,
#모든 정렬은 오름차순, 내림차순 하고싶다면 정렬된 행렬에 [::-1]로 인덱싱


[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
원본 배열: [[[20 19 18 17 16]
  [15 14 13 12 11]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]]]
정렬된 배열: [[[16 17 18 19 20]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
[[[10  9  8  7  6]
  [ 5  4  3  2  1]]

 [[20 19 18 17 16]
  [15 14 13 12 11]]]
[[2 3 1]
 [6 5 8]]
None
[[2 3 1]
 [6 5 8]]
[[2 3 1]
 [6 5 8]]
[0 1 1 2 2 3 4 5]


### Task

In [46]:
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# ndarray.ravel(): 2차원 넘파이 배열을 1차원 넘파이 배열로 변경(mutable)
# ndarray.flatten(): 2차원 넘파이 배열을 1차원 넘파이 배열로 변경(immutable) -> 주소에 직접접근을 막고 새로 만든 배열로 사용

# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]
ndarray1 = np.array(array1)
print(np.argsort(ndarray1[1])[::-1])
print(ndarray1[0][[0,1]])
print(ndarray1[0][np.argsort(ndarray1[1])[::-1]])

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]
ndarray2= np.array(array2)
ndarray2_age = ndarray2[1].astype(np.int8)
age_sort_index=np.argsort(ndarray2_age)[::-1]
print(ndarray2[0][age_sort_index])

print(ndarray2[0][np.argsort(ndarray2[2])[::-1]])


# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['영국', '러시아', '남아프리카 공화국', '미국', '한국'], ['-0.6%', '-0.3%', '12.2%', '11.4%', '1.7%']]
ndarray3 =np.array(array3)

ndarray3_percent = np.vectorize(lambda s : s.replace("%",""))(ndarray3[1]).astype(np.float16)
print(ndarray3[0][np.argsort(ndarray3_percent)])



[4 3 2 1 0]
['Mango' 'Apple']
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']
['길동' '마이콜' '또치' '둘리' '도너']
['도너' '마이콜' '둘리' '길동' '또치']
['영국' '러시아' '한국' '미국' '남아프리카 공화국']


In [51]:
# 다음 연립방정식을 전치 행렬과 행렬 내적 
# 그리고 역행렬(np.linalg.inv())을 통해 해결하세요.

# k = [[k1], [k2]]
# A = [[x1, x2], [y1, y2]]
# w = [[w1], [w2]]

# k1 = x1w1 + x2w2
# k2 = y1w1 + y2w2
# k = Aw

ndarray1 = np.array([[1,2,3],[1,2,1],[1,0,3]])
ndarray2 = np.array([1,3,5])

ndarray1_reverse = np.linalg.inv(ndarray1)
print(ndarray1_reverse.dot(ndarray2.T))





# x + 2y + 3z = 1
# x + 2y + z = 3
# x + 3z = 5

# 다음 행렬을 내적하세요.

# '''
# A1      A2
# 1 2 3   7 8
# 4 5 6   9 10
#         11 12
# '''

[ 8. -2. -1.]
